run:
  timeout: 5m
  issues:
    exclude-dirs:
    - tmp
    exclude-rules:
      - text: "directory not found"
      - path: run
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - copyloopvar
    - sloglint
    - unconvert
    - gosec
    - noctx
    - gocritic
    - testifylint
    - goconst
    - nilerr
    - contextcheck
    - whitespace