name: Lint

on:
  push:
    branches: [main, pipelines-test]
  pull_request:
    branches: [main, pipelines-test]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Print debug info
        run: |
          ls -la
          cat go.mod        

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Format code
        run: goimports -w .

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.58.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64.2
          args: --timeout=5m -v --build-tags=integration