name: Lint

on:
  push:
    branches: [main, pipelines-test]
  pull_request:
    branches: [main, pipelines-test]

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Set Go env
        run: |
          go env -w GOMODCACHE=${{ github.workspace }}/go-mod
          go env -w GOCACHE=${{ github.workspace }}/go-build

      - name: Debug file structure
        run: ls -la

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.65.0
          args: run --timeout=5m -v